import express from "express";
import * as controller from "../../controller/admin/user.controller" ;
import multer from "multer";
import { uploadCloud } from "../../middleware/admin/uploadCloud.middleware";
import { requireAuth } from "../../middleware/admin/auth.middlewares";
const upload = multer({ storage: multer.memoryStorage() });
const router = express.Router();
router.get("/register", controller.register);
router.post("/register", controller.postRegister);
router.get("/login",controller.login);
router.post("/login",controller.postLogin);
router.get("/logout",controller.logout);
export const userRouter = router;